"""Build the JobsLocked North Florida (jl-mold-fl) prospecting report.

Reads data/pipeline.db (maps_companies table), renders a branded summary
HTML page + PDF, and writes the two outreach CSV exports. Output lands in
geo-prospecting/claim-site/dist/report/jl-mold-fl/ — the shared dist tree
used for every Antek Automation report deploy (project antek-claim).

Usage:
    uv run python src/reports/build_report.py
"""
from __future__ import annotations

import csv
import sqlite3
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DB_PATH = ROOT / "data" / "pipeline.db"

# Shared Antek brand tokens live in the geo-prospecting repo.
GEO_PROSPECTING = ROOT.parent / "geo-prospecting"
sys.path.insert(0, str(GEO_PROSPECTING))
from src.reports import brand  # noqa: E402

from jinja2 import Template  # noqa: E402

OUT_DIR = GEO_PROSPECTING / "claim-site" / "dist" / "report" / "jl-mold-fl"

FULL_COLUMNS = [
    "id", "place_id", "name", "address", "city", "county", "zip", "phone",
    "website", "rating", "review_count", "categories", "business_status",
    "franchise_flag", "license_verified", "matched_license_number",
    "matched_principal_name", "match_confidence", "is_duplicate",
    "dup_group_id", "lead_mill_suspect", "owner_name_found", "owner_confirmed",
    "email", "email_source", "booking_widget", "chat_widget", "emergency_247",
    "form_only_contact", "pain_score", "segment", "score_notes",
]

OUTREACH_COLUMNS = [
    "name", "owner_name_found", "email", "email_source", "phone", "city",
    "county", "website", "rating", "review_count", "pain_score", "segment",
]
OUTREACH_HEADER = [
    "company", "principal_owner", "email", "email_source", "phone", "city",
    "county", "website", "rating", "review_count", "pain_score", "segment",
]

SEGMENT_LABEL = {
    "tier1": "Tier 1 — has web presence, likely misses calls",
    "tier2": "Tier 2 — presence but weak reviews",
    "tier3": "Tier 3 — little/no online presence",
}
SEGMENT_SHORT = {
    "tier1": "Has web presence, likely misses calls",
    "tier2": "Presence but weak reviews",
    "tier3": "Little/no online presence",
}


def fetch_rows(conn: sqlite3.Connection) -> list[sqlite3.Row]:
    conn.row_factory = sqlite3.Row
    return conn.execute("SELECT * FROM maps_companies ORDER BY id").fetchall()


def write_full_csv(rows: list[sqlite3.Row], path: Path) -> int:
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(FULL_COLUMNS)
        for r in rows:
            w.writerow([r[c] for c in FULL_COLUMNS])
    return len(rows)


def write_outreach_csv(rows: list[sqlite3.Row], path: Path) -> int:
    scored = [r for r in rows if r["pain_score"] is not None]
    scored.sort(key=lambda r: (r["pain_score"] or 0), reverse=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(OUTREACH_HEADER)
        for r in scored:
            w.writerow([r[c] for c in OUTREACH_COLUMNS])
    return len(scored)


def build_stats(rows: list[sqlite3.Row]) -> dict:
    total = len(rows)
    scored = [r for r in rows if r["pain_score"] is not None]
    counties = sorted({r["county"] for r in rows if r["county"]})
    seg_counts: dict[str, int] = {}
    for r in rows:
        seg = r["segment"]
        if seg:
            seg_counts[seg] = seg_counts.get(seg, 0) + 1
    county_counts: dict[str, int] = {}
    for r in rows:
        c = r["county"] or "Unknown"
        county_counts[c] = county_counts.get(c, 0) + 1
    county_rows = sorted(county_counts.items(), key=lambda kv: (-kv[1], kv[0]))
    dup_count = sum(1 for r in rows if r["is_duplicate"])
    lead_mill_count = sum(1 for r in rows if r["lead_mill_suspect"])
    email_count = sum(1 for r in rows if r["email"])
    top_prospects = sorted(scored, key=lambda r: (r["pain_score"] or 0), reverse=True)[:20]
    return {
        "total": total,
        "scored": len(scored),
        "counties": counties,
        "county_count": len(counties),
        "seg_counts": seg_counts,
        "county_rows": county_rows,
        "dup_count": dup_count,
        "lead_mill_count": lead_mill_count,
        "email_count": email_count,
        "top_prospects": top_prospects,
    }


TEMPLATE = """<!-- generated by build_report.py -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>North Florida Mold Remediation — Prospect List Report | Antek Automation</title>
<style>
{{ font_face }}
{{ base_css }}
body { padding: 0; }
.wrap { max-width: 980px; margin: 0 auto; padding: 40px 24px 80px; }
header.hero { background: var(--charcoal); color: #fff; padding: 48px 24px; }
header.hero .wrap { padding-top: 0; padding-bottom: 0; }
header.hero h1 { font-size: 30px; margin-bottom: 8px; }
header.hero p { opacity: .85; font-size: 14px; }
.stat-row { display: flex; gap: 16px; flex-wrap: wrap; margin: 28px 0; }
.stat { flex: 1 1 160px; }
.stat .num { font-family: var(--font_mono, 'JetBrains Mono'); font-size: 30px; font-weight: 700; }
.stat .label { font-size: 12px; text-transform: uppercase; letter-spacing: .04em; opacity: .75; }
h2 { font-size: 20px; margin: 40px 0 14px; padding-bottom: 8px; border-bottom: 3px solid var(--charcoal); }
.seg-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 14px; margin-bottom: 20px; }
.seg-card .count { font-family: var(--font_mono, 'JetBrains Mono'); font-size: 26px; font-weight: 700; }
.seg-card .meaning { font-size: 12px; margin-top: 4px; }
table.small th, table.small td { font-size: 11px; padding: 5px 7px; }
.downloads { display: flex; gap: 14px; flex-wrap: wrap; margin: 18px 0 8px; }
.dl { display: inline-block; padding: 12px 18px; background: var(--coral); color: #fff; font-weight: 700;
      text-decoration: none; border: var(--border); box-shadow: var(--shadow); font-size: 13px; }
.dl.alt { background: var(--charcoal); }
.dl.outline { background: #fff; color: var(--charcoal); }
.note { font-size: 12px; background: var(--cream); padding: 14px 16px; border: var(--border); margin: 14px 0; }
footer { margin-top: 60px; padding-top: 20px; border-top: 2px solid var(--charcoal); font-size: 11px; opacity: .7; }
</style>
</head>
<body>
<header class="hero">
  <div class="wrap">
    <h1>North Florida Mold Remediation — Prospect List</h1>
    <p>JobsLocked lead generation output · Google Maps discovery cross-referenced against FL DBPR license registry · generated for Antek Automation internal use</p>
  </div>
</header>
<div class="wrap">

  <div class="stat-row">
    <div class="stat card"><div class="num">{{ stats.total }}</div><div class="label">Companies found</div></div>
    <div class="stat card"><div class="num">{{ stats.county_count }}</div><div class="label">North FL counties</div></div>
    <div class="stat card"><div class="num">{{ stats.scored }}</div><div class="label">Scored &amp; segmented</div></div>
    <div class="stat card"><div class="num">{{ stats.email_count }}</div><div class="label">Emails found</div></div>
  </div>

  <h2>Segment breakdown</h2>
  <div class="seg-grid">
    {% for seg in ['tier1','tier2','tier3'] %}
    <div class="seg-card card {{ 'coral' if seg=='tier1' else ('sage' if seg=='tier2' else 'cream') }}">
      <div class="count">{{ stats.seg_counts.get(seg, 0) }}</div>
      <div class="meaning">{{ seg_short[seg] }}</div>
    </div>
    {% endfor %}
  </div>

  <h2>Downloads</h2>
  <div class="downloads">
    <a class="dl" href="./jl-mold-fl-full.csv">Full CSV — all {{ stats.total }} rows, all columns (incl. emails)</a>
    <a class="dl alt" href="./jl-mold-fl-outreach.csv">Outreach CSV — {{ stats.scored }} scored rows, sorted by pain score</a>
    <a class="dl outline" href="./jl-mold-fl-summary.pdf">PDF — this summary page</a>
  </div>

  <h2>County breakdown</h2>
  <table class="small">
    <thead><tr><th>County</th><th>Companies</th></tr></thead>
    <tbody>
    {% for county, count in stats.county_rows %}
      <tr><td>{{ county }}</td><td>{{ count }}</td></tr>
    {% endfor %}
    </tbody>
  </table>

  <h2>Top prospects by pain score (sample of {{ stats.top_prospects|length }})</h2>
  <table class="small">
    <thead><tr>
      <th>Company</th><th>City</th><th>County</th><th>Phone</th><th>Website</th>
      <th>Rating</th><th>Pain score</th><th>Segment</th>
    </tr></thead>
    <tbody>
    {% for r in stats.top_prospects %}
      <tr>
        <td>{{ r['name'] }}</td>
        <td>{{ r['city'] or '' }}</td>
        <td>{{ r['county'] or '' }}</td>
        <td>{{ r['phone'] or '' }}</td>
        <td>{{ (r['website'] or '')[:40] }}</td>
        <td>{{ r['rating'] or '' }}</td>
        <td>{{ r['pain_score'] }}</td>
        <td>{{ r['segment'] }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <h2>Methodology</h2>
  <p>Companies discovered via Google Maps search sweeps across North Florida
  mold inspection / remediation search terms, then cross-referenced against
  the Florida DBPR mold-related license registry to confirm active licensure
  where a match was available. Each company was enriched with website,
  review, and contact-widget signals, then scored for outreach "pain" —
  businesses with weak or absent digital presence score highest, since they
  are the most likely to be missing calls or losing bookings to competitors
  who show up online.</p>

  <h2>Data caveats</h2>
  <div class="note">
    <strong>{{ stats.lead_mill_count }} rows</strong> flagged as lead-mill
    suspects (directory/aggregator listings masquerading as local businesses)
    were excluded from scoring.<br>
    <strong>{{ stats.dup_count }} rows</strong> were flagged as duplicates
    (same business found via multiple map sweeps) and are not double-counted
    in the totals above.
  </div>

  <footer>
    {{ brand.COMPANY_NAME }} · {{ brand.OPERATOR }} · {{ brand.WEBSITE }} ·
    internal prospecting report, not a client deliverable.
  </footer>
</div>
</body>
</html>
"""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    rows = fetch_rows(conn)

    n_full = write_full_csv(rows, OUT_DIR / "jl-mold-fl-full.csv")
    n_outreach = write_outreach_csv(rows, OUT_DIR / "jl-mold-fl-outreach.csv")
    stats = build_stats(rows)
    conn.close()

    html = Template(TEMPLATE).render(
        stats=stats,
        seg_short=SEGMENT_SHORT,
        seg_label=SEGMENT_LABEL,
        brand=brand,
        font_face=brand.font_face_css(),
        base_css=brand.base_css(),
    )
    (OUT_DIR / "index.html").write_text(html, encoding="utf-8")

    # PDF of the summary page only (not raw data tables' full CSVs).
    from weasyprint import HTML
    HTML(string=html, base_url=str(OUT_DIR)).write_pdf(str(OUT_DIR / "jl-mold-fl-summary.pdf"))

    print(f"Full CSV: {n_full} rows")
    print(f"Outreach CSV: {n_outreach} rows")
    print(f"Wrote {OUT_DIR}/index.html, jl-mold-fl-full.csv, jl-mold-fl-outreach.csv, jl-mold-fl-summary.pdf")


if __name__ == "__main__":
    main()
